Prompt color in separate file, support different profiles.

diff --git a/configs/bashrc b/configs/bashrc
--- a/configs/bashrc
+++ b/configs/bashrc
@@ -53,52 +53,17 @@ if [ -n "$force_color_prompt" ]; then
     fi
 fi
 
-# define a function '_short_wdir' that takes the value of pwd and returns
-# a truncated version (with a prefix to indicate truncation) if the length
-# is above a certain limit, otherwise just $HOME is substitued by '~'
-_short_wdir() {
-    # how many characters of the $PWD should be kept
-	local pwdmaxlen=34
-    # use '~' instead of full path for homedir
-	local shortPWD="${PWD/$HOME/\~}"
-    # indicator that there has been directory truncation:
-	local trunc_symbol="«"
-	if [ ${#shortPWD} -gt $pwdmaxlen ] ; then
-		local pwdoffset=$(( ${#shortPWD} - $pwdmaxlen ))
-		printf "${trunc_symbol}${shortPWD:$pwdoffset:$pwdmaxlen}"
-	else
-		printf "${shortPWD}"
-	fi
-}
-
-# define color shorthands
-blw='\[\033[00m\]'     # black-white
-red='\[\033[0;31m\]'   # red
-grn='\[\033[0;32m\]'   # green
-ylw='\[\033[0;33m\]'   # yellow
-blu='\[\033[0;34m\]'   # blue
-bred='\[\033[01;31m\]' # bold red
-bgrn='\[\033[01;32m\]' # bold green
-bylw='\[\033[01;33m\]' # bold yellow
-bblu='\[\033[01;34m\]' # bold blue
-
 # schroot struggles with TERM-settings in a screen-session, so:
 if [ -n "$debian_chroot" ] && [ "$TERM" == "screen.rxvt" ] ; then
 	export TERM="screen"
 fi
 
-# set a prefix if we're inside a screen since old screen-versions (or
-# non-ubuntu ones) can't be easily distinguished from a regular session
-[ "$TERM" == "screen" ] && scn="$bylw[S]$blw"
-
-# red hostname if we're on SSH (doesn't work for dropbear):
-if [ -n "$SSH_TTY" ] ; then
-	host=$blw$red'@\h'
+if ! [ -f ~/.bash_prompt.inc.sh ]; then
+    echo "WARN: Couldn't find ~/.bash_prompt.inc.sh!"
+    color_prompt="no"
 else
-	host=$blw$bgrn'@\h'
+    source ~/.bash_prompt.inc.sh
 fi
-# blue directory name
-wdir=$blw':'$bblu'$(_short_wdir)'$blw'\$ '
 
 if [ "$color_prompt" = yes ]; then
 	PS1=$scn$red'${debian_chroot:+($debian_chroot)}'$grn'\u'$host$wdir
